[package]
name = "kinopoisk_bot_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.13"
teloxide = { version = "0.11.3", features = ["macros", "auto-send"] }
log = "0.4.17"
futures = "0.3.25"
pretty_env_logger = "0.4.0"
tokio = { version = "1.24.2", features = ["rt-multi-thread", "macros"] }
uuid = "1.2.2"
serde = { version = "1.0.152", features = ["derive"] }
dotenv = "0.15.0"
