[package]
name = "kinopoisk_bot_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.11"
teloxide = { version = "0.11.1", features = ["macros", "auto-send"] }
log = "0.4"
futures = "0.3"
pretty_env_logger = "0.4"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
uuid = "1.2.1"
serde = { version = "1.0.147", features = ["derive"] }
